[[module]]
name = "power"
uuid = "abbbd3832ad747a0a1b0cd1b3c6d6579"
[module.config]
profiles = [
  {state = 0},
  {state = 1, wakeup_mask = 149, delay_s = 1300}, # 5 min timer before sleep.
  {state = 2, wakeup_mask = 20, delay_s = 1720}, # 2 min timer before hibernate.
]

[[module]]
name = "timer"
uuid = "018e7e898ac74a06936fab03b5fc6094"

[[module]]
name = "adc"
uuid = "2e48782d9d424b678c583755877fa687"
[module.config]
thresholds = [
  {index = 2, value = 11100}, # 11.1V
  {index = 2, value = 12000}, # 12.0V
  {index = 2, value = 18000}, # 18.0V
  {index = 2, value = 22200}, # 22.2V
  {index = 2, value = 24000}, # 24.0V
]

[[module]]
name = "io"
uuid = "2fa4f8500e044f92b1368164d8e1e49c"
[module.config]
analog_inputs = [
  {adc_input = 0, digital_input = 50, set_value = 5000, clear_value = 2000},
]

[[module]]
name = "kv"
uuid = "1d376724b74c40bc86aa4ee57441b9dd"
[module.config]
sync_frequency_minutes = 15
defaults = [
  {key = 1, value = 0}, # Used for restricted mode status.
  {key = 4, value = 0}, # Used for accumulator 0 key.
  {key = 5, value = 0}, # Used for accumulator 1 key.
]

[[module]]
name = "report"
uuid = "69fdf7ae3d5011eab77f2e728ce88125"
[module.config]
inbound_server = "m7-gw.internal.telematics.equipment"
inbound_port = 5683
maintenance_server = "m7.m.internal.telematics.equipment"
maintenance_inbound_port = 5683
maintenance_checkin_interval = 1440
reports = [
  # Periodic message.
  {uri_index = 1, block_bitmask = 279, block_config = []},

   # Ident message.
  {uri_index = 2, block_bitmask = 0, block_config = []},

   # IO CoS.
  {uri_index = 0, block_bitmask = 51, block_config = [
    {index = 5, arg = 1},
  ]},

      # J1939 Comm Status.
  {uri_index = 0, block_bitmask = 53, block_config = [
    {index = 5, arg = 20},
  ]},

      # J1939 Fault Resync.
  {uri_index = 0, block_bitmask = 40, block_config = [
    {index = 5, arg = 24},
  ]},

      # J1939 Faults.
  {uri_index = 0, block_bitmask = 60, block_config = [
    {index = 5, arg = 23},
  ]},

      # Register Threshold.
  {uri_index = 0, block_bitmask = 50, block_config = [
    {index = 5, arg = 11},
  ]},

      # GPS Fix Report.
  {uri_index = 0, block_bitmask = 48, block_config = [
    {index = 5, arg = 5},
  ]},
]

[[module]]
name = "register"
uuid = "a0d76aa3becf4bdabf54ebc6c6c21945"
[module.config]
registers = [
  {type = 0},
  {type = 1, id = 39, arg = 300},
  {type = 2, id = 3, arg = 120},
]

[[module]]
name = "j1939"
uuid = "ac0e4b9c567a4f629b6f472d9ca138ce"
[module.config]
change_of_state = []
raw = []
thresholds = []

[[module]]
name = "ble"
uuid = "20e7068614e94d4980cbffce06f71433"
[module.config]
connect_message_threshold = 8
disconnect_message_threshold = 4
scan_message_threshold = 0
max_scan_results = 30
sort_by = 4

[[module]]
name = "cron"
uuid = "c609d032bc7844aba78ef3044d9fbec5"
resource_count_test = 10

[[module]]
name = "gps"
uuid = "1e7710e2853642a4b7924afadeee0da6"

[network]
blocks = [
  {type = "sleep-behaviour", args = {active_profile = "0", sleep_profile = "100"}},
  {type = "kv-accumulators", tag = "acc0", args = {start = "io.input_high.0", stop = "io.input_low.0", acc_index = "4"}},
  {type = "kv-accumulators", tag = "acc1", args = {start = "io.input_high.1", stop = "io.input_low.1", acc_index = "5"}},
  {type = "periodic-messages", args = {early_on_interval = "300000", on_interval = "900000", off_interval = "60", delay_interval = "240000", report_index = "0", sleep_profile = "1"}},
  {type = "ident-messages", args = {duration = "45000", report_index = "1"}},
  {type = "input-cos", tag = "input_1", args = {input = "0", report_index = "2", event_signal = "1", delay_interval = "1000"}},
  {type = "input-cos", tag = "input_2", args = {input = "1", report_index = "2", event_signal = "2", delay_interval = "1000"}},
  {type = "input-cos", tag = "input_3", args = {input = "2", report_index = "2", event_signal = "3", delay_interval = "1000"}},
  {type = "input-cos", tag = "bnd", args = {input = "3", report_index = "2", event_signal = "4", delay_interval = "1000"}},
  {type = "j1939", args = {enable = "io.input_high.0", disable = "io.input_low.0", comm_status_index = "3", can_reset = "io.input_high.0", enable_condition = "io.is_high.0 or io.is_high.1"}},
  {type = "j1939-fault", args = {enable_condition = "io.is_high.0", resync_report_index = "8", fault_report_index = "9"}},
  {type = "bluetooth", args = {enable = "io.input_high.0", disable = "io.input_low.0"}},
  {type = "restricted-mode", args = {frequency = "5000", rm_register = "1", unrestricted_value = "0", restricted_value = "1"}},
  {type = "analog-threshold", args = {A_low = "0", A_high = "1", system_median = "2", B_low = "3", B_high = "4", report_index = "10", below_signal = "30", above_signal = "31", debounce_interval = "120000", boot_index = "100", threshold_index = "101", state = "1"}},
  {type = "gps-fix", args = {report_index = "11", signal = "0"}},
]
